include: package:lints/recommended.yaml
analyzer:
  language:
    strict-inference: true
    strict-casts: true
    strict-raw-types: true
linter:
  rules:
    - avoid_dynamic_calls
    - avoid_final_parameters
    - avoid_print
    - avoid_unused_constructor_parameters
    - camel_case_types
    - combinators_ordering
    - comment_references
    - invalid_case_patterns
    - no_self_assignments
    - no_wildcard_variable_uses
    - omit_local_variable_types
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_relative_imports
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - unreachable_from_main