# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyze:
      - command: "dart analyze --fatal-infos ."
      - command: "dart format --set-exit-if-changed ."
  - unit_test:
      - command: "dart test --platform vm test/all_test.dart"
      - command: "dart test --platform chrome test/all_test.dart"

cache:
  directories:
    - .dart_tool/build