# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyze:
      - command: "dartanalyzer --fatal-infos ."
      - command: "dartfmt --dry-run --set-exit-if-changed ."
  - unit_test:
      - command: "pub run test --platform vm"
      - command: "pub run test --platform chrome"

cache:
  directories:
    - .dart_tool/build